# TYPE  DATABASE        USER            ADDRESS                 METHOD

# 로컬에서의 모든 연결 허용
host    all             all             0.0.0.0/0               md5
host    all             all             ::/0                    md5